%
% Status : main Dynare file 
%
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

clear all
tic;
global M_ oo_ options_ ys0_ ex0_ estimation_info
options_ = [];
M_.fname = 'dynareFLR_phipi05';
%
% Some global variables initialization
%
global_initialization;
diary off;
diary('dynareFLR_phipi05.log');
M_.exo_names = 'eps_z';
M_.exo_names_tex = '{\epsilon_z}';
M_.exo_names_long = 'Technology innovation';
M_.exo_names = char(M_.exo_names, 'eps_zu');
M_.exo_names_tex = char(M_.exo_names_tex, '{\epsilon_{\sigma_z}}');
M_.exo_names_long = char(M_.exo_names_long, 'Technology uncertainty innovation');
M_.exo_names = char(M_.exo_names, 'eps_R');
M_.exo_names_tex = char(M_.exo_names_tex, '{\epsilon_R}');
M_.exo_names_long = char(M_.exo_names_long, 'Interest rate innovation');
M_.exo_names = char(M_.exo_names, 'eps_Ru');
M_.exo_names_tex = char(M_.exo_names_tex, '{\epsilon_{\sigma_R}}');
M_.exo_names_long = char(M_.exo_names_long, 'Interest rate uncertainty innovation');
M_.endo_names = 'c';
M_.endo_names_tex = '{c}';
M_.endo_names_long = 'Consumption';
M_.endo_names = char(M_.endo_names, 'R');
M_.endo_names_tex = char(M_.endo_names_tex, '{R}');
M_.endo_names_long = char(M_.endo_names_long, 'Short-term nominal interest rate (gross)');
M_.endo_names = char(M_.endo_names, 'RReal');
M_.endo_names_tex = char(M_.endo_names_tex, '{R^r}');
M_.endo_names_long = char(M_.endo_names_long, 'Real Interest Rate');
M_.endo_names = char(M_.endo_names, 'Pii');
M_.endo_names_tex = char(M_.endo_names_tex, '{\Pi}');
M_.endo_names_long = char(M_.endo_names_long, 'Inflation rate (gross)');
M_.endo_names = char(M_.endo_names, 'y');
M_.endo_names_tex = char(M_.endo_names_tex, '{y}');
M_.endo_names_long = char(M_.endo_names_long, 'Aggregate output');
M_.endo_names = char(M_.endo_names, 'x');
M_.endo_names_tex = char(M_.endo_names_tex, '{x}');
M_.endo_names_long = char(M_.endo_names_long, 'Relative price of intermediate goods');
M_.endo_names = char(M_.endo_names, 'm');
M_.endo_names_tex = char(M_.endo_names_tex, '{m}');
M_.endo_names_long = char(M_.endo_names_long, 'Number of matches');
M_.endo_names = char(M_.endo_names, 'u');
M_.endo_names_tex = char(M_.endo_names_tex, '{u}');
M_.endo_names_long = char(M_.endo_names_long, 'Unemployment rate');
M_.endo_names = char(M_.endo_names, 'us');
M_.endo_names_tex = char(M_.endo_names_tex, '{u^s}');
M_.endo_names_long = char(M_.endo_names_long, 'Number of searching workers');
M_.endo_names = char(M_.endo_names, 'v');
M_.endo_names_tex = char(M_.endo_names_tex, '{v}');
M_.endo_names_long = char(M_.endo_names_long, 'Number of vacancies');
M_.endo_names = char(M_.endo_names, 'f');
M_.endo_names_tex = char(M_.endo_names_tex, '{f}');
M_.endo_names_long = char(M_.endo_names_long, 'Job finding rate');
M_.endo_names = char(M_.endo_names, 'h');
M_.endo_names_tex = char(M_.endo_names_tex, '{h}');
M_.endo_names_long = char(M_.endo_names_long, 'Vacancy filling rate');
M_.endo_names = char(M_.endo_names, 'n');
M_.endo_names_tex = char(M_.endo_names_tex, '{n}');
M_.endo_names_long = char(M_.endo_names_long, 'Employment');
M_.endo_names = char(M_.endo_names, 'J');
M_.endo_names_tex = char(M_.endo_names_tex, '{J}');
M_.endo_names_long = char(M_.endo_names_long, 'Value of a firm (with match)');
M_.endo_names = char(M_.endo_names, 'w');
M_.endo_names_tex = char(M_.endo_names_tex, '{w}');
M_.endo_names_long = char(M_.endo_names_long, 'Actual wage');
M_.endo_names = char(M_.endo_names, 'lambda');
M_.endo_names_tex = char(M_.endo_names_tex, '{\lambda}');
M_.endo_names_long = char(M_.endo_names_long, 'Marginal utility');
M_.endo_names = char(M_.endo_names, 'theta');
M_.endo_names_tex = char(M_.endo_names_tex, '{\theta}');
M_.endo_names_long = char(M_.endo_names_long, 'Labor market tightness');
M_.endo_names = char(M_.endo_names, 'ac');
M_.endo_names_tex = char(M_.endo_names_tex, '{ac}');
M_.endo_names_long = char(M_.endo_names_long, 'Price adjustment costs');
M_.endo_names = char(M_.endo_names, 'z');
M_.endo_names_tex = char(M_.endo_names_tex, '{z}');
M_.endo_names_long = char(M_.endo_names_long, 'Productivity');
M_.endo_names = char(M_.endo_names, 'sigma_z');
M_.endo_names_tex = char(M_.endo_names_tex, '{\sigma_z}');
M_.endo_names_long = char(M_.endo_names_long, 'Technology shock volatility');
M_.endo_names = char(M_.endo_names, 'sigma_R');
M_.endo_names_tex = char(M_.endo_names_tex, '{\sigma_R}');
M_.endo_names_long = char(M_.endo_names_long, 'Interest rate shock volatility');
M_.endo_names = char(M_.endo_names, 'e_R');
M_.endo_names_tex = char(M_.endo_names_tex, '{e_R}');
M_.endo_names_long = char(M_.endo_names_long, 'Interest rate shock process');
M_.endo_names = char(M_.endo_names, 'RP');
M_.endo_names_tex = char(M_.endo_names_tex, '{RP}');
M_.endo_names_long = char(M_.endo_names_long, 'Risk premium');
M_.endo_names = char(M_.endo_names, 'S');
M_.endo_names_tex = char(M_.endo_names_tex, '{S}');
M_.endo_names_long = char(M_.endo_names_long, 'Consumption state');
M_.endo_names = char(M_.endo_names, 'expGrowth');
M_.endo_names_tex = char(M_.endo_names_tex, '{expGrowth}');
M_.endo_names_long = char(M_.endo_names_long, 'Expected growth');
M_.endo_names = char(M_.endo_names, 'logu');
M_.endo_names_tex = char(M_.endo_names_tex, 'logu');
M_.endo_names_long = char(M_.endo_names_long, 'Log of unemployment');
M_.endo_names = char(M_.endo_names, 'logtheta');
M_.endo_names_tex = char(M_.endo_names_tex, 'logtheta');
M_.endo_names_long = char(M_.endo_names_long, 'Log of tightness');
M_.endo_names = char(M_.endo_names, 'logz');
M_.endo_names_tex = char(M_.endo_names_tex, 'logz');
M_.endo_names_long = char(M_.endo_names_long, 'Log of productivity');
M_.endo_names = char(M_.endo_names, 'RP1');
M_.endo_names_tex = char(M_.endo_names_tex, 'RP1');
M_.endo_names_long = char(M_.endo_names_long, 'Risk premium - 1 period ahead');
M_.endo_names = char(M_.endo_names, 'SDF');
M_.endo_names_tex = char(M_.endo_names_tex, 'SDF');
M_.endo_names_long = char(M_.endo_names_long, 'SDF');
M_.endo_names = char(M_.endo_names, 'RFR');
M_.endo_names_tex = char(M_.endo_names_tex, '{RFR}');
M_.endo_names_long = char(M_.endo_names_long, 'Risk-free return');
M_.endo_names = char(M_.endo_names, 'Dividend');
M_.endo_names_tex = char(M_.endo_names_tex, '{Dividend}');
M_.endo_names_long = char(M_.endo_names_long, 'Dividend');
M_.endo_names = char(M_.endo_names, 'Elambda1');
M_.endo_names_tex = char(M_.endo_names_tex, 'Elambda1');
M_.endo_names_long = char(M_.endo_names_long, 'Expected marginal utility');
M_.endo_names = char(M_.endo_names, 'CovJElambda1');
M_.endo_names_tex = char(M_.endo_names_tex, 'CovJElambda1');
M_.endo_names_long = char(M_.endo_names_long, 'Covariance between MU and J');
M_.endo_names = char(M_.endo_names, 'JCheck');
M_.endo_names_tex = char(M_.endo_names_tex, 'JCheck');
M_.endo_names_long = char(M_.endo_names_long, 'JCheck');
M_.endo_names = char(M_.endo_names, 'JNoCov');
M_.endo_names_tex = char(M_.endo_names_tex, 'JNoCov');
M_.endo_names_long = char(M_.endo_names_long, 'JNoCov');
M_.endo_names = char(M_.endo_names, 'JNoElambda1');
M_.endo_names_tex = char(M_.endo_names_tex, 'JNoElambda1');
M_.endo_names_long = char(M_.endo_names_long, 'JNoElambda1');
M_.endo_names = char(M_.endo_names, 'REquity');
M_.endo_names_tex = char(M_.endo_names_tex, 'REquity');
M_.endo_names_long = char(M_.endo_names_long, 'REquity');
M_.endo_names = char(M_.endo_names, 'n_Obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'n\_Obs');
M_.endo_names_long = char(M_.endo_names_long, 'n_Obs');
M_.endo_names = char(M_.endo_names, 'z_Obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'z\_Obs');
M_.endo_names_long = char(M_.endo_names_long, 'z_Obs');
M_.endo_names = char(M_.endo_names, 'sigma_z_Obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'sigma\_z\_Obs');
M_.endo_names_long = char(M_.endo_names_long, 'sigma_z_Obs');
M_.endo_names = char(M_.endo_names, 'SDF1');
M_.endo_names_tex = char(M_.endo_names_tex, 'SDF1');
M_.endo_names_long = char(M_.endo_names_long, 'SDF1');
M_.endo_names = char(M_.endo_names, 'SDF2');
M_.endo_names_tex = char(M_.endo_names_tex, 'SDF2');
M_.endo_names_long = char(M_.endo_names_long, 'SDF2');
M_.endo_names = char(M_.endo_names, 'SDF3');
M_.endo_names_tex = char(M_.endo_names_tex, 'SDF3');
M_.endo_names_long = char(M_.endo_names_long, 'SDF3');
M_.endo_names = char(M_.endo_names, 'SDF4');
M_.endo_names_tex = char(M_.endo_names_tex, 'SDF4');
M_.endo_names_long = char(M_.endo_names_long, 'SDF4');
M_.endo_names = char(M_.endo_names, 'SDF5');
M_.endo_names_tex = char(M_.endo_names_tex, 'SDF5');
M_.endo_names_long = char(M_.endo_names_long, 'SDF5');
M_.endo_names = char(M_.endo_names, 'SDF6');
M_.endo_names_tex = char(M_.endo_names_tex, 'SDF6');
M_.endo_names_long = char(M_.endo_names_long, 'SDF6');
M_.endo_names = char(M_.endo_names, 'SDF7');
M_.endo_names_tex = char(M_.endo_names_tex, 'SDF7');
M_.endo_names_long = char(M_.endo_names_long, 'SDF7');
M_.endo_names = char(M_.endo_names, 'SDF8');
M_.endo_names_tex = char(M_.endo_names_tex, 'SDF8');
M_.endo_names_long = char(M_.endo_names_long, 'SDF8');
M_.endo_names = char(M_.endo_names, 'SDF9');
M_.endo_names_tex = char(M_.endo_names_tex, 'SDF9');
M_.endo_names_long = char(M_.endo_names_long, 'SDF9');
M_.endo_names = char(M_.endo_names, 'SDF10');
M_.endo_names_tex = char(M_.endo_names_tex, 'SDF10');
M_.endo_names_long = char(M_.endo_names_long, 'SDF10');
M_.endo_names = char(M_.endo_names, 'SDF11');
M_.endo_names_tex = char(M_.endo_names_tex, 'SDF11');
M_.endo_names_long = char(M_.endo_names_long, 'SDF11');
M_.endo_names = char(M_.endo_names, 'SDF12');
M_.endo_names_tex = char(M_.endo_names_tex, 'SDF12');
M_.endo_names_long = char(M_.endo_names_long, 'SDF12');
M_.endo_names = char(M_.endo_names, 'RE1');
M_.endo_names_tex = char(M_.endo_names_tex, 'RE1');
M_.endo_names_long = char(M_.endo_names_long, 'RE1');
M_.endo_names = char(M_.endo_names, 'RE2');
M_.endo_names_tex = char(M_.endo_names_tex, 'RE2');
M_.endo_names_long = char(M_.endo_names_long, 'RE2');
M_.endo_names = char(M_.endo_names, 'RE3');
M_.endo_names_tex = char(M_.endo_names_tex, 'RE3');
M_.endo_names_long = char(M_.endo_names_long, 'RE3');
M_.endo_names = char(M_.endo_names, 'RE4');
M_.endo_names_tex = char(M_.endo_names_tex, 'RE4');
M_.endo_names_long = char(M_.endo_names_long, 'RE4');
M_.endo_names = char(M_.endo_names, 'RE5');
M_.endo_names_tex = char(M_.endo_names_tex, 'RE5');
M_.endo_names_long = char(M_.endo_names_long, 'RE5');
M_.endo_names = char(M_.endo_names, 'RE6');
M_.endo_names_tex = char(M_.endo_names_tex, 'RE6');
M_.endo_names_long = char(M_.endo_names_long, 'RE6');
M_.endo_names = char(M_.endo_names, 'RE7');
M_.endo_names_tex = char(M_.endo_names_tex, 'RE7');
M_.endo_names_long = char(M_.endo_names_long, 'RE7');
M_.endo_names = char(M_.endo_names, 'RE8');
M_.endo_names_tex = char(M_.endo_names_tex, 'RE8');
M_.endo_names_long = char(M_.endo_names_long, 'RE8');
M_.endo_names = char(M_.endo_names, 'RE9');
M_.endo_names_tex = char(M_.endo_names_tex, 'RE9');
M_.endo_names_long = char(M_.endo_names_long, 'RE9');
M_.endo_names = char(M_.endo_names, 'RE10');
M_.endo_names_tex = char(M_.endo_names_tex, 'RE10');
M_.endo_names_long = char(M_.endo_names_long, 'RE10');
M_.endo_names = char(M_.endo_names, 'RE11');
M_.endo_names_tex = char(M_.endo_names_tex, 'RE11');
M_.endo_names_long = char(M_.endo_names_long, 'RE11');
M_.endo_names = char(M_.endo_names, 'RE12');
M_.endo_names_tex = char(M_.endo_names_tex, 'RE12');
M_.endo_names_long = char(M_.endo_names_long, 'RE12');
M_.endo_names = char(M_.endo_names, 'RFR1');
M_.endo_names_tex = char(M_.endo_names_tex, 'RFR1');
M_.endo_names_long = char(M_.endo_names_long, 'RFR1');
M_.endo_names = char(M_.endo_names, 'RFR2');
M_.endo_names_tex = char(M_.endo_names_tex, 'RFR2');
M_.endo_names_long = char(M_.endo_names_long, 'RFR2');
M_.endo_names = char(M_.endo_names, 'RFR3');
M_.endo_names_tex = char(M_.endo_names_tex, 'RFR3');
M_.endo_names_long = char(M_.endo_names_long, 'RFR3');
M_.endo_names = char(M_.endo_names, 'RFR4');
M_.endo_names_tex = char(M_.endo_names_tex, 'RFR4');
M_.endo_names_long = char(M_.endo_names_long, 'RFR4');
M_.endo_names = char(M_.endo_names, 'RFR5');
M_.endo_names_tex = char(M_.endo_names_tex, 'RFR5');
M_.endo_names_long = char(M_.endo_names_long, 'RFR5');
M_.endo_names = char(M_.endo_names, 'RFR6');
M_.endo_names_tex = char(M_.endo_names_tex, 'RFR6');
M_.endo_names_long = char(M_.endo_names_long, 'RFR6');
M_.endo_names = char(M_.endo_names, 'RFR7');
M_.endo_names_tex = char(M_.endo_names_tex, 'RFR7');
M_.endo_names_long = char(M_.endo_names_long, 'RFR7');
M_.endo_names = char(M_.endo_names, 'RFR8');
M_.endo_names_tex = char(M_.endo_names_tex, 'RFR8');
M_.endo_names_long = char(M_.endo_names_long, 'RFR8');
M_.endo_names = char(M_.endo_names, 'RFR9');
M_.endo_names_tex = char(M_.endo_names_tex, 'RFR9');
M_.endo_names_long = char(M_.endo_names_long, 'RFR9');
M_.endo_names = char(M_.endo_names, 'RFR10');
M_.endo_names_tex = char(M_.endo_names_tex, 'RFR10');
M_.endo_names_long = char(M_.endo_names_long, 'RFR10');
M_.endo_names = char(M_.endo_names, 'RFR11');
M_.endo_names_tex = char(M_.endo_names_tex, 'RFR11');
M_.endo_names_long = char(M_.endo_names_long, 'RFR11');
M_.endo_names = char(M_.endo_names, 'RFR12');
M_.endo_names_tex = char(M_.endo_names_tex, 'RFR12');
M_.endo_names_long = char(M_.endo_names_long, 'RFR12');
M_.endo_names = char(M_.endo_names, 'REcum');
M_.endo_names_tex = char(M_.endo_names_tex, 'REcum');
M_.endo_names_long = char(M_.endo_names_long, 'REcum');
M_.endo_names = char(M_.endo_names, 'RFRcum');
M_.endo_names_tex = char(M_.endo_names_tex, 'RFRcum');
M_.endo_names_long = char(M_.endo_names_long, 'RFRcum');
M_.endo_names = char(M_.endo_names, 'EJ1');
M_.endo_names_tex = char(M_.endo_names_tex, 'EJ1');
M_.endo_names_long = char(M_.endo_names_long, 'EJ1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_254');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_254');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_254');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_260');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_260');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_260');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_266');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_266');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_266');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_272');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_272');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_272');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_278');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_278');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_278');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_284');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_284');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_284');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_290');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_290');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_290');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_296');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_296');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_296');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_302');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_302');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_302');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_308');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_308');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_308');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_314');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_314');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_314');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_382');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_382');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_382');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_393');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_393');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_393');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_404');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_404');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_404');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_415');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_415');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_415');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_426');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_426');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_426');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_437');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_437');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_437');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_448');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_448');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_448');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_459');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_459');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_459');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_470');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_470');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_470');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_481');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_481');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_481');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LEAD_492');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LEAD\_492');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LEAD_492');
M_.param_names = 'betta';
M_.param_names_tex = '{\betta}';
M_.param_names_long = 'Subjective discount factor';
M_.param_names = char(M_.param_names, 'xi');
M_.param_names_tex = char(M_.param_names_tex, '{\xi}');
M_.param_names_long = char(M_.param_names_long, 'Inverse elasticity of intertemporal substitution');
M_.param_names = char(M_.param_names, 'eta');
M_.param_names_tex = char(M_.param_names_tex, '{\eta}');
M_.param_names_long = char(M_.param_names_long, 'Elasticity of substitution b/w differentiated products');
M_.param_names = char(M_.param_names, 'alpha');
M_.param_names_tex = char(M_.param_names_tex, '{\alpha}');
M_.param_names_long = char(M_.param_names_long, 'Elasticity of matching w.r.t. u');
M_.param_names = char(M_.param_names, 'delta');
M_.param_names_tex = char(M_.param_names_tex, '{\rho}');
M_.param_names_long = char(M_.param_names_long, 'Exogenous job destruction rate');
M_.param_names = char(M_.param_names, 'kappa');
M_.param_names_tex = char(M_.param_names_tex, '{\kappa}');
M_.param_names_long = char(M_.param_names_long, 'Vacancy posting fixed cost');
M_.param_names = char(M_.param_names, 'Omega_p');
M_.param_names_tex = char(M_.param_names_tex, '{\Omega_p}');
M_.param_names_long = char(M_.param_names_long, 'Price adjustment cost');
M_.param_names = char(M_.param_names, 'phi_pi');
M_.param_names_tex = char(M_.param_names_tex, '{\phi_{\pi}}');
M_.param_names_long = char(M_.param_names_long, 'Taylor rule parameter for inflation');
M_.param_names = char(M_.param_names, 'phi_y');
M_.param_names_tex = char(M_.param_names_tex, '{\phi_{y}}');
M_.param_names_long = char(M_.param_names_long, 'Taylor rule parameter for output');
M_.param_names = char(M_.param_names, 'phi_r');
M_.param_names_tex = char(M_.param_names_tex, '{\phi_{r}}');
M_.param_names_long = char(M_.param_names_long, 'Taylor rule interest rate smoothing');
M_.param_names = char(M_.param_names, 'omega');
M_.param_names_tex = char(M_.param_names_tex, '{\omega}');
M_.param_names_long = char(M_.param_names_long, 'Bargaining weight for workers');
M_.param_names = char(M_.param_names, 'rho_z');
M_.param_names_tex = char(M_.param_names_tex, '{\rho_z}');
M_.param_names_long = char(M_.param_names_long, 'Technology shock, persistence');
M_.param_names = char(M_.param_names, 'rho_sigma_z');
M_.param_names_tex = char(M_.param_names_tex, '{\rho_{\sigma_z}}');
M_.param_names_long = char(M_.param_names_long, 'Technoloy uncertainty shock, persistence');
M_.param_names = char(M_.param_names, 'sigma_zbar');
M_.param_names_tex = char(M_.param_names_tex, '{\bar{\sigma}_z}');
M_.param_names_long = char(M_.param_names_long, 'Technology uncertainty shock, mean value');
M_.param_names = char(M_.param_names, 'sigma_sigma_z');
M_.param_names_tex = char(M_.param_names_tex, '{\sigma_{\sigma_z}}');
M_.param_names_long = char(M_.param_names_long, 'Technology uncertainty shock, sd of innovation');
M_.param_names = char(M_.param_names, 'chi');
M_.param_names_tex = char(M_.param_names_tex, '{\chi}');
M_.param_names_long = char(M_.param_names_long, 'Strike value');
M_.param_names = char(M_.param_names, 'psi');
M_.param_names_tex = char(M_.param_names_tex, '{\bar{\mu}}');
M_.param_names_long = char(M_.param_names_long, 'Matching efficiency');
M_.param_names = char(M_.param_names, 'CCHabit1');
M_.param_names_tex = char(M_.param_names_tex, '{\rho_{s}');
M_.param_names_long = char(M_.param_names_long, 'Habit formation, persistence');
M_.param_names = char(M_.param_names, 'CCHabit2');
M_.param_names_tex = char(M_.param_names_tex, '{State}');
M_.param_names_long = char(M_.param_names_long, 'Habit formation, average state');
M_.param_names = char(M_.param_names, 'sigma_RBar');
M_.param_names_tex = char(M_.param_names_tex, 'sigma\_RBar');
M_.param_names_long = char(M_.param_names_long, 'sigma_RBar');
M_.param_names = char(M_.param_names, 'rho_sigma_R');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_sigma\_R');
M_.param_names_long = char(M_.param_names_long, 'rho_sigma_R');
M_.param_names = char(M_.param_names, 'sigma_sigma_R');
M_.param_names_tex = char(M_.param_names_tex, 'sigma\_sigma\_R');
M_.param_names_long = char(M_.param_names_long, 'sigma_sigma_R');
M_.param_names = char(M_.param_names, 'rho_e_R');
M_.param_names_tex = char(M_.param_names_tex, 'rho\_e\_R');
M_.param_names_long = char(M_.param_names_long, 'rho_e_R');
M_.param_names = char(M_.param_names, 'zBar');
M_.param_names_tex = char(M_.param_names_tex, '{\bar{Z}}');
M_.param_names_long = char(M_.param_names_long, 'Technology shock, mean value');
M_.param_names = char(M_.param_names, 'PiiBar');
M_.param_names_tex = char(M_.param_names_tex, '{\bar{\pi}}');
M_.param_names_long = char(M_.param_names_long, 'Inflation, steady-state value');
M_.param_names = char(M_.param_names, 'uBar');
M_.param_names_tex = char(M_.param_names_tex, '{\bar{u}}');
M_.param_names_long = char(M_.param_names_long, 'Unemployment rate, steady-state value');
M_.param_names = char(M_.param_names, 'hBar');
M_.param_names_tex = char(M_.param_names_tex, '{\bar{q}^v}');
M_.param_names_long = char(M_.param_names_long, 'Vacancy filling rate, steady-state value');
M_.param_names = char(M_.param_names, 'css');
M_.param_names_tex = char(M_.param_names_tex, '{\bar{C}}');
M_.param_names_long = char(M_.param_names_long, 'css');
M_.param_names = char(M_.param_names, 'Rss');
M_.param_names_tex = char(M_.param_names_tex, '{\bar{R}}');
M_.param_names_long = char(M_.param_names_long, 'Rss');
M_.param_names = char(M_.param_names, 'Piiss');
M_.param_names_tex = char(M_.param_names_tex, '{\bar{\pi}}');
M_.param_names_long = char(M_.param_names_long, 'Piiss');
M_.param_names = char(M_.param_names, 'yss');
M_.param_names_tex = char(M_.param_names_tex, '{\bar{Y}}');
M_.param_names_long = char(M_.param_names_long, 'yss');
M_.param_names = char(M_.param_names, 'xss');
M_.param_names_tex = char(M_.param_names_tex, '{\bar{x}}');
M_.param_names_long = char(M_.param_names_long, 'xss');
M_.param_names = char(M_.param_names, 'mss');
M_.param_names_tex = char(M_.param_names_tex, '{\bar{m}}');
M_.param_names_long = char(M_.param_names_long, 'mss');
M_.param_names = char(M_.param_names, 'vss');
M_.param_names_tex = char(M_.param_names_tex, '{\bar{v}}');
M_.param_names_long = char(M_.param_names_long, 'vss');
M_.param_names = char(M_.param_names, 'fss');
M_.param_names_tex = char(M_.param_names_tex, '{\bar{f}');
M_.param_names_long = char(M_.param_names_long, 'fss');
M_.param_names = char(M_.param_names, 'hss');
M_.param_names_tex = char(M_.param_names_tex, '{\bar{h}}');
M_.param_names_long = char(M_.param_names_long, 'hss');
M_.param_names = char(M_.param_names, 'nss');
M_.param_names_tex = char(M_.param_names_tex, '{\bar{n}}');
M_.param_names_long = char(M_.param_names_long, 'nss');
M_.param_names = char(M_.param_names, 'uss');
M_.param_names_tex = char(M_.param_names_tex, '{\bar{u}}');
M_.param_names_long = char(M_.param_names_long, 'uss');
M_.param_names = char(M_.param_names, 'usss');
M_.param_names_tex = char(M_.param_names_tex, '{\bar{u}^s}');
M_.param_names_long = char(M_.param_names_long, 'usss');
M_.param_names = char(M_.param_names, 'Jss');
M_.param_names_tex = char(M_.param_names_tex, '{\bar{J}^F}');
M_.param_names_long = char(M_.param_names_long, 'Jss');
M_.param_names = char(M_.param_names, 'lambdass');
M_.param_names_tex = char(M_.param_names_tex, '{\bar{\lambda}}');
M_.param_names_long = char(M_.param_names_long, 'lambdass');
M_.param_names = char(M_.param_names, 'zss');
M_.param_names_tex = char(M_.param_names_tex, '{\bar{Z}}');
M_.param_names_long = char(M_.param_names_long, 'zss');
M_.param_names = char(M_.param_names, 'wss');
M_.param_names_tex = char(M_.param_names_tex, '{\bar{w}}');
M_.param_names_long = char(M_.param_names_long, 'wss');
M_.param_names = char(M_.param_names, 'sss');
M_.param_names_tex = char(M_.param_names_tex, '{\bar{s}}');
M_.param_names_long = char(M_.param_names_long, 'sss');
M_.param_names = char(M_.param_names, 'thetass');
M_.param_names_tex = char(M_.param_names_tex, '{\bar{\theta}}');
M_.param_names_long = char(M_.param_names_long, 'thetass');
M_.param_names = char(M_.param_names, 'StickyDuration');
M_.param_names_tex = char(M_.param_names_tex, '{\hat{\Omega}_p}');
M_.param_names_long = char(M_.param_names_long, 'Duration of price stickiness');
M_.param_names = char(M_.param_names, 'thetp');
M_.param_names_tex = char(M_.param_names_tex, '{\tilde{\Omega}_p}');
M_.param_names_long = char(M_.param_names_long, 'Calvo equivalent');
M_.exo_det_nbr = 0;
M_.exo_nbr = 4;
M_.endo_nbr = 102;
M_.param_nbr = 47;
M_.orig_endo_nbr = 80;
M_.aux_vars(1).endo_index = 81;
M_.aux_vars(1).type = 0;
M_.aux_vars(2).endo_index = 82;
M_.aux_vars(2).type = 0;
M_.aux_vars(3).endo_index = 83;
M_.aux_vars(3).type = 0;
M_.aux_vars(4).endo_index = 84;
M_.aux_vars(4).type = 0;
M_.aux_vars(5).endo_index = 85;
M_.aux_vars(5).type = 0;
M_.aux_vars(6).endo_index = 86;
M_.aux_vars(6).type = 0;
M_.aux_vars(7).endo_index = 87;
M_.aux_vars(7).type = 0;
M_.aux_vars(8).endo_index = 88;
M_.aux_vars(8).type = 0;
M_.aux_vars(9).endo_index = 89;
M_.aux_vars(9).type = 0;
M_.aux_vars(10).endo_index = 90;
M_.aux_vars(10).type = 0;
M_.aux_vars(11).endo_index = 91;
M_.aux_vars(11).type = 0;
M_.aux_vars(12).endo_index = 92;
M_.aux_vars(12).type = 0;
M_.aux_vars(13).endo_index = 93;
M_.aux_vars(13).type = 0;
M_.aux_vars(14).endo_index = 94;
M_.aux_vars(14).type = 0;
M_.aux_vars(15).endo_index = 95;
M_.aux_vars(15).type = 0;
M_.aux_vars(16).endo_index = 96;
M_.aux_vars(16).type = 0;
M_.aux_vars(17).endo_index = 97;
M_.aux_vars(17).type = 0;
M_.aux_vars(18).endo_index = 98;
M_.aux_vars(18).type = 0;
M_.aux_vars(19).endo_index = 99;
M_.aux_vars(19).type = 0;
M_.aux_vars(20).endo_index = 100;
M_.aux_vars(20).type = 0;
M_.aux_vars(21).endo_index = 101;
M_.aux_vars(21).type = 0;
M_.aux_vars(22).endo_index = 102;
M_.aux_vars(22).type = 0;
M_.Sigma_e = zeros(4, 4);
M_.Correlation_matrix = eye(4, 4);
M_.H = 0;
M_.Correlation_matrix_ME = 1;
M_.sigma_e_is_diagonal = 1;
options_.block=0;
options_.bytecode=0;
options_.use_dll=0;
erase_compiled_function('dynareFLR_phipi05_static');
erase_compiled_function('dynareFLR_phipi05_dynamic');
M_.lead_lag_incidence = [
 0 10 0;
 1 11 0;
 0 12 0;
 0 13 112;
 0 14 113;
 0 15 0;
 0 16 0;
 0 17 0;
 0 18 0;
 0 19 0;
 0 20 0;
 0 21 0;
 2 22 0;
 0 23 114;
 0 24 0;
 0 25 115;
 0 26 0;
 0 27 0;
 3 28 0;
 4 29 0;
 5 30 0;
 6 31 0;
 0 32 0;
 7 33 0;
 8 34 0;
 0 35 0;
 0 36 0;
 9 37 116;
 0 38 0;
 0 39 0;
 0 40 0;
 0 41 0;
 0 42 0;
 0 43 0;
 0 44 0;
 0 45 0;
 0 46 0;
 0 47 0;
 0 48 0;
 0 49 0;
 0 50 0;
 0 51 0;
 0 52 0;
 0 53 0;
 0 54 0;
 0 55 0;
 0 56 0;
 0 57 0;
 0 58 0;
 0 59 0;
 0 60 0;
 0 61 0;
 0 62 0;
 0 63 0;
 0 64 0;
 0 65 0;
 0 66 0;
 0 67 0;
 0 68 0;
 0 69 0;
 0 70 0;
 0 71 0;
 0 72 0;
 0 73 0;
 0 74 0;
 0 75 0;
 0 76 0;
 0 77 0;
 0 78 0;
 0 79 0;
 0 80 0;
 0 81 0;
 0 82 0;
 0 83 0;
 0 84 0;
 0 85 0;
 0 86 0;
 0 87 0;
 0 88 0;
 0 89 0;
 0 90 117;
 0 91 118;
 0 92 119;
 0 93 120;
 0 94 121;
 0 95 122;
 0 96 123;
 0 97 124;
 0 98 125;
 0 99 126;
 0 100 127;
 0 101 128;
 0 102 129;
 0 103 130;
 0 104 131;
 0 105 132;
 0 106 133;
 0 107 134;
 0 108 135;
 0 109 136;
 0 110 137;
 0 111 138;]';
M_.nstatic = 67;
M_.nfwrd   = 26;
M_.npred   = 8;
M_.nboth   = 1;
M_.nsfwrd   = 27;
M_.nspred   = 9;
M_.ndynamic   = 35;
M_.equations_tags = {
  1 , 'name' , 'Habit' ;
  3 , 'name' , 'Marginal utility' ;
  4 , 'name' , 'Bond Euler' ;
  5 , 'name' , 'Searching workers' ;
  6 , 'name' , 'Matching function' ;
  7 , 'name' , 'Job finding rate ' ;
  8 , 'name' , 'Vacancy filling rate' ;
  9 , 'name' , 'Labor market tightness' ;
  10 , 'name' , 'Employment LoM' ;
  11 , 'name' , 'Unemployment rate' ;
  12 , 'name' , 'Wage' ;
  13 , 'name' , 'Production Function' ;
  14 , 'name' , 'Free entry' ;
  15 , 'name' , 'Equity Euler' ;
  16 , 'name' , 'Expected marginal utility' ;
  17 , 'name' , 'Covariance term' ;
  18 , 'name' , 'Equity Euler - check' ;
  19 , 'name' , 'Equity Euler - no covariance' ;
  20 , 'name' , 'Equity Euler - no expected marginal utility' ;
  21 , 'name' , 'Phillips Curve' ;
  22 , 'name' , 'Price adjustment cost' ;
  23 , 'name' , 'Resource constraint' ;
  24 , 'name' , 'Taylor rule' ;
  25 , 'name' , 'Technology shock' ;
  26 , 'name' , 'Technology uncertainty shock' ;
  27 , 'name' , 'Interest rate shock' ;
  28 , 'name' , 'Interest rate volatility' ;
  29 , 'name' , 'Real interest rate' ;
  30 , 'name' , 'Return on equity' ;
  31 , 'name' , 'Dividend' ;
  32 , 'name' , 'Stochastic discount factor' ;
  45 , 'name' , 'Risk-free rate(s)' ;
  59 , 'name' , 'Risk premium' ;
};
M_.static_and_dynamic_models_differ = 0;
M_.exo_names_orig_ord = [1:4];
M_.maximum_lag = 1;
M_.maximum_lead = 1;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 1;
oo_.steady_state = zeros(102, 1);
M_.maximum_exo_lag = 0;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(4, 1);
M_.params = NaN(47, 1);
M_.NNZDerivatives = zeros(3, 1);
M_.NNZDerivatives(1) = 296;
M_.NNZDerivatives(2) = 468;
M_.NNZDerivatives(3) = 3147;
load Parameters
set_param_value('betta',vPar.betta);
M_.params( 3 ) = 10;
eta = M_.params( 3 );
M_.params( 4 ) = 0.5;
alpha = M_.params( 4 );
M_.params( 25 ) = 1.0016;
PiiBar = M_.params( 25 );
M_.params( 27 ) = 0.331;
hBar = M_.params( 27 );
M_.params( 26 ) = 0.064;
uBar = M_.params( 26 );
M_.params( 24 ) = 1;
zBar = M_.params( 24 );
M_.params( 5 ) = 0.028;
delta = M_.params( 5 );
set_param_value('kappa',vPar.kappa);
set_param_value('CCHabit1',vPar.CCHabit1);
set_param_value('CCHabit2',vPar.CCHabit2);
set_param_value('xi',vPar.xi);
set_param_value('phi_pi',5);
set_param_value('phi_y',vPar.phi_y);
set_param_value('phi_r',vPar.phi_r);
set_param_value('rho_z',vPar.rho_z);
set_param_value('sigma_zbar',vPar.sigma_zbar);
set_param_value('sigma_sigma_z',vPar.sigma_sigma_z);
set_param_value('rho_sigma_z',vPar.rho_sigma_z);
set_param_value('sigma_RBar',vPar.sigma_RBar);
set_param_value('rho_sigma_R',vPar.rho_sigma_R);
set_param_value('rho_e_R',vPar.rho_e_R);
set_param_value('sigma_sigma_R',vPar.sigma_sigma_R);
M_.params( 42 ) = M_.params(24);
zss = M_.params( 42 );
M_.params( 30 ) = M_.params(25);
Piiss = M_.params( 30 );
M_.params( 38 ) = M_.params(26);
uss = M_.params( 38 );
M_.params( 36 ) = M_.params(27);
hss = M_.params( 36 );
M_.params( 37 ) = 1-M_.params(38);
nss = M_.params( 37 );
M_.params( 33 ) = M_.params(5)*M_.params(37);
mss = M_.params( 33 );
M_.params( 39 ) = 1-M_.params(37)*(1-M_.params(5));
usss = M_.params( 39 );
M_.params( 44 ) = log(M_.params(19));
sss = M_.params( 44 );
M_.params( 35 ) = M_.params(33)/M_.params(39);
fss = M_.params( 35 );
M_.params( 34 ) = M_.params(33)/M_.params(36);
vss = M_.params( 34 );
M_.params( 45 ) = M_.params(34)/M_.params(39);
thetass = M_.params( 45 );
M_.params( 31 ) = M_.params(37)*M_.params(42);
yss = M_.params( 31 );
M_.params( 17 ) = M_.params(33)/(M_.params(39)^M_.params(4)*M_.params(34)^(1-M_.params(4)));
psi = M_.params( 17 );
M_.params( 28 ) = M_.params(31);
css = M_.params( 28 );
M_.params( 41 ) = M_.params(19)^(-M_.params(2))*M_.params(28)^(-M_.params(2));
lambdass = M_.params( 41 );
M_.params( 29 ) = M_.params(30)/M_.params(1);
Rss = M_.params( 29 );
M_.params( 32 ) = (M_.params(3)-1)/M_.params(3);
xss = M_.params( 32 );
M_.params( 40 ) = 1/M_.params(36)*M_.params(6);
Jss = M_.params( 40 );
M_.params( 43 ) = M_.params(42)*M_.params(32)-(1-(1-M_.params(5))*M_.params(1))*M_.params(40);
wss = M_.params( 43 );
set_param_value('chi',vPar.chi);
M_.params( 11 ) = (M_.params(43)-M_.params(16))/(M_.params(42)*M_.params(32)-M_.params(16));
omega = M_.params( 11 );
M_.params( 46 ) = 9;
StickyDuration = M_.params( 46 );
M_.params( 47 ) = 1-1/M_.params(46);
thetp = M_.params( 47 );
M_.params( 7 ) = M_.params(3)*M_.params(32)/M_.params(30)^2*M_.params(47)/(1-M_.params(47))/(1-M_.params(1)*M_.params(47));
Omega_p = M_.params( 7 );
%
% SHOCKS instructions
%
make_ex_;
M_.exo_det_length = 0;
M_.Sigma_e(1, 1) = 1;
M_.Sigma_e(2, 2) = 1;
M_.Sigma_e(3, 3) = 1;
M_.Sigma_e(4, 4) = 1;
resid;
steady;
oo_.dr.eigval = check(M_,options_,oo_);
options_.irf = 0;
options_.k_order_solver = 1;
options_.order = 3;
options_.pruning = 1;
var_list_=[];
info = stoch_simul(var_list_);
vNames = M_.endo_names; 
tic
IrfPeriods = 60;                
BurninPeriods = 10000;   
mEpsZero      = zeros(BurninPeriods+IrfPeriods,M_.exo_nbr); 
mIrfZero      = simult_(oo_.dr.ys,oo_.dr,mEpsZero,options_.order)'; 
vEMAS         = mIrfZero(1+BurninPeriods,:); 
mEps = zeros(BurninPeriods+IrfPeriods,M_.exo_nbr);
mEps(1+BurninPeriods,strmatch('eps_zu',M_.exo_names,'exact')) = 1; 
mIrf = simult_(oo_.dr.ys,oo_.dr,mEps,options_.order)';
mIrfProp = (mIrf(1+BurninPeriods+1:1+BurninPeriods+IrfPeriods,:)-mIrfZero(1+BurninPeriods+1:1+BurninPeriods+IrfPeriods,:))./repmat(vEMAS,IrfPeriods,1); 
mIrfProp(abs(mIrfProp)<1e-12)=0;
mIRFProp_zUncertainty_EMAS = mIrfProp;
IrfPeriods = 60;                
BurninPeriods = 10000;                 
mEpsZero      = zeros(BurninPeriods+IrfPeriods,M_.exo_nbr); 
mIrfZero      = simult_(oo_.dr.ys,oo_.dr,mEpsZero,options_.order)'; 
vEMAS         = mIrfZero(1+BurninPeriods,:); 
mEps = zeros(BurninPeriods+IrfPeriods,M_.exo_nbr);
mEps(1+BurninPeriods,strmatch('eps_Ru',M_.exo_names,'exact')) = 1; 
mIrf = simult_(oo_.dr.ys,oo_.dr,mEps,options_.order)';
mIrfProp = (mIrf(1+BurninPeriods+1:1+BurninPeriods+IrfPeriods,:)-mIrfZero(1+BurninPeriods+1:1+BurninPeriods+IrfPeriods,:))./repmat(vEMAS,IrfPeriods,1); 
mIrfProp(abs(mIrfProp)<1e-12)=0;
mIRFProp_RUncertainty_EMAS = mIrfProp;
save("../Output/IRFs/IRFs_FLR_phipi05", 'vEMAS', 'vNames', 'mIRFProp_zUncertainty_EMAS', 'mIRFProp_RUncertainty_EMAS') 
save('dynareFLR_phipi05_results.mat', 'oo_', 'M_', 'options_');
if exist('estim_params_', 'var') == 1
  save('dynareFLR_phipi05_results.mat', 'estim_params_', '-append');
end
if exist('bayestopt_', 'var') == 1
  save('dynareFLR_phipi05_results.mat', 'bayestopt_', '-append');
end
if exist('dataset_', 'var') == 1
  save('dynareFLR_phipi05_results.mat', 'dataset_', '-append');
end
if exist('estimation_info', 'var') == 1
  save('dynareFLR_phipi05_results.mat', 'estimation_info', '-append');
end


disp(['Total computing time : ' dynsec2hms(toc) ]);
if ~isempty(lastwarn)
  disp('Note: warning(s) encountered in MATLAB/Octave code')
end
diary off
